id: I96B3A2C7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:22:14+00:00'
last_modified: '2022-06-07T14:00:11.664653+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD2074
  title: གསུང་འབུམ། གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B752:
      image_group_id: I1CZ978
      title: ''
      total_pages: 990
      order: 1
      base_file: B752.txt
    C949:
      image_group_id: I1CZ979
      title: ''
      total_pages: 1200
      order: 2
      base_file: C949.txt
    A3BF:
      image_group_id: I01JW11564
      title: ''
      total_pages: 1034
      order: 3
      base_file: A3BF.txt
    B4F8:
      image_group_id: I1CZ981
      title: ''
      total_pages: 650
      order: 4
      base_file: B4F8.txt
    B944:
      image_group_id: I01JW11565
      title: ''
      total_pages: 624
      order: 5
      base_file: B944.txt
    E43D:
      image_group_id: I1CZ983
      title: ''
      total_pages: 382
      order: 6
      base_file: E43D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
