id: I96B3A2C7
legacy_id: P001678
ocr_import_info:
  bdrc_scan_id: W1PD2074
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T17:20:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T04:20:48.945609+00:00'
last_modified: 2022-09-01 12:21:17.014474
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD2074
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1PD2074
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ།
  author: རྒྱ་ཀོང་མཁན་ཆེན་གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.8242416709738701
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I01JW11565:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW11565
      total_pages: 624
      volume_number: 5
    order: 5
    base_file: I01JW11565.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8242416709738701
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
